project_root: /mounts/u-amo-d1/adibm-data/projects/latin
# model_path: outputs/2024-03-30/01-47-55/pretrain
model_path: outputs/2024-03-30/01-47-55/train
data_split_percentage: 1
data_path: data/keyed/canon/
max_length: 512