project_root: /mounts/u-amo-d1/adibm-data/projects/latin
data_split_percentage: 1
data_path: data/
data_type: decrExcerpt
max_length: 512
# data_stats_path: data/data_stats/data_stats.csv
# test_out_path: data/test_unkeyed_data.csv
# train_out_path: data/train_unkeyed_data.csv
data_stats_path: data/data_stats/decr_data_stats.csv
test_out_path: data/test_decr_data.csv
train_out_path: data/train_decr_data.csv
mlm_model_path: outputs/2024-03-30/01-47-55/train
tokenizer_name: silencesys/paraphrase-xlm-r-multilingual-v1-fine-tuned-for-medieval-latin
train_data_split_percentage: 1
train_batch_size: 30
eval_batch_size: 9
epochs: 200
# epochs: 1
eval_steps : 50
out_path: results
contrastive_model_path: ""
# contrastive_model_path: outputs/2024-07-23/18-57-40/results